name: Quick Test - File Upload

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'OBS bucket name'
        required: false
        type: string
      test_file_content:
        description: 'Content for test file'
        required: false
        default: 'Hello from GitHub Actions!'
        type: string

env:
  OBS_BUCKET: ${{ inputs.bucket || secrets.OBS_BUCKET }}
  OBS_ACCESS_KEY: ${{ secrets.OBS_ACCESS_KEY }}
  OBS_SECRET_KEY: ${{ secrets.OBS_SECRET_KEY }}

jobs:
  quick-upload-test:
    runs-on: ubuntu-latest
    name: Quick Upload Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "${{ inputs.test_file_content }}" > test-file.txt
          echo "Created test file with content:"
          cat test-file.txt

      - name: Test file upload
        uses: ./
        with:
          access_key: ${{ env.OBS_ACCESS_KEY }}
          secret_key: ${{ env.OBS_SECRET_KEY }}
          region: cn-north-4
          bucket: ${{ env.OBS_BUCKET }}
          operation: upload
          local_path: test-file.txt
          obs_path: gh-obs-helper/quick-test/
          progress: true
          dry_run: false

      - name: Verify upload
        run: |
          echo "Upload completed successfully!"
          echo "Check your OBS bucket '${{ env.OBS_BUCKET }}' for the file at 'quick-test/test-file.txt'"

      - name: Cleanup
        if: always()
        run: |
          rm -f test-file.txt
